version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD", "--appendonly", "yes", "--save", "60 10000", "--maxmemory-policy", "allkeys-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  redis-data:
    driver: local

networks:
  backend:
    driver: bridge